apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moondream-server-ingress
  namespace: llm
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-aliyun
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
  - host: moondream.sgprivate.code27.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: moondream-service
            port:
              number: 5000
  - host: moondream.sgllm.code27.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: moondream-service
            port:
              number: 5000
  tls:
  - hosts:
    - moondream.sgprivate.code27.co
    - moondream.sgllm.code27.co
    secretName: moondream-server-tls
